# Generated by Django 2.2 on 2020-01-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_url',
            field=models.TextField(default='missing.png'),
            preserve_default=False,
        ),
    ]
